### ISSUE TITLE
The file or directory to be published does not exist: /Users/Sites/test/vendor/bower/bootstrap-switch/dist

### ISSUE THREAD

**Issue by dev3k** [2amigos/yii2-switch-widget#9]
i got this problem trying to install the widget, 

**The file or directory to be published does not exist: /Users/Sites/test/vendor/bower/bootstrap-switch/dist**

it worked by changing this 
```php
class SwitchAsset extends AssetBundle
{
    public $sourcePath = '@bower/bootstrap-switch/dist';
```
to 
```php
class SwitchAsset extends AssetBundle
{
    public $sourcePath = '@bower/bower-asset/bootstrap-switch/dist';
```
any thoughts ?!

**Comment by dev3k** [comment]
never mind it worked after deleting vendor folder then composer clear-cache and composer update

**Comment by timmy78** [comment]
Still doesn't work for me :confused:

**Comment by dev3k** [comment]
try also composer self-update
